
spring:
  application:
    name: movie-gallery
  datasource:
    url: jdbc:mysql://localhost:3306/movie_gallery
    username: root
    password: root
mybatis:
  mapper-locations: classpath:sqlmap/**/*.xml
  configuration:
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
logging:
  level:
    com.example.moviegallery.dao: debug

# ===== manually added library
socketio: # com.corundumstudio.socketio.Configuration
  port: 8181
  allowCustomRequests: true
  bossCount: 0 # 0 = current_processors_amount * 2
  workCount: 0 # 0 = current_processors_amount * 2
  pingInterval: 25000
  pingTimeout: 60000
  upgradeTimeout: 10000
